export const headers = [
  { title: 'S:N', key: 'sn', align: 'start', sortable: false },
  { title: 'Image', key: 'image', align: 'start', sortable: false },
  { title: 'Name', key: 'name', align: 'start' },
  { title: 'Category', key: 'category', align: 'start' },
  { title: 'Sub Category', key: 'sub_category', align: 'start' },
  { title: 'Brand', key: 'brand', align: 'start' },
  { title: 'Color', key: 'color', align: 'start' },
  { title: 'Price', key: 'price', align: 'start' },
  { title: 'Compare Price', key: 'compare_price', align: 'start' },
   { title: 'Is Featured', key: 'is_featured', align: 'start' },
    { title: 'Created At', key: 'created_at', sortable: true },
  { title: 'Status', key: 'status', align: 'start' },
  { title: 'Actions', key: 'actions', align: 'end', sortable: false },
];